#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2154
# Packaging phase: install pacman + AUR packages.

PACO_PACKAGING="${PACO_INSTALL}/packaging"

run_logged "${PACO_PACKAGING}/yay.sh"
run_logged "${PACO_PACKAGING}/zsh.sh"
run_logged "${PACO_PACKAGING}/tools-tier1.sh"
run_logged "${PACO_PACKAGING}/tools-tier2.sh"
run_logged "${PACO_PACKAGING}/fonts.sh"
run_logged "${PACO_PACKAGING}/starship.sh"
run_logged "${PACO_PACKAGING}/tools-tier4.sh"
run_logged "${PACO_PACKAGING}/dev-tools.sh"
run_logged "${PACO_PACKAGING}/ghostty.sh"
run_logged "${PACO_PACKAGING}/tools-tier3.sh"
run_logged "${PACO_PACKAGING}/nvim.sh"
run_logged "${PACO_PACKAGING}/podman.sh"
run_logged "${PACO_PACKAGING}/hyprland.sh"
run_logged "${PACO_PACKAGING}/sddm.sh"
run_logged "${PACO_PACKAGING}/waybar-mako.sh"
run_logged "${PACO_PACKAGING}/launcher.sh"
run_logged "${PACO_PACKAGING}/boot-stack.sh"
run_logged "${PACO_PACKAGING}/system-services.sh"
run_logged "${PACO_PACKAGING}/chrome.sh"
run_logged "${PACO_PACKAGING}/icons.sh"
run_logged "${PACO_PACKAGING}/webapps.sh"
run_logged "${PACO_PACKAGING}/hardware-vulkan.sh"
run_logged "${PACO_PACKAGING}/native-apps.sh"
run_logged "${PACO_PACKAGING}/file-managers.sh"
